[project]
title = "Resume Builder"
version = "0.1.0"
port = 8501

[branding]
name = "Resume Builder"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#003ca8"

[data.csv]
type = "csv"
path = "resume.csv"
delimiter = ","
header = true

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"